### ISSUE TITLE
Failed to load new dex on Android API 22 

### ISSUE THREAD

**Issue by listerily** [listerily/ModdedBE#10]
Failed to launch minecraft by loading AgentMainActivity.dex.
A java class is defined to launch Minecraft, but when I call `startActivity`, the app crashed and prints
```
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.listerily.moddedbe/com.mojang.minecraftpe.AgentMainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.mojang.minecraftpe.AgentMainActivity" on path: DexPathList[[zip file "/data/app/net.listerily.moddedbe-2/base.apk"],nativeLibraryDirectories=[/data/app/net.listerily.moddedbe-2/lib/x86, /vendor/lib, /system/lib]]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2236)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mojang.minecraftpe.AgentMainActivity" on path: DexPathList[[zip file "/data/app/net.listerily.moddedbe-2/base.apk"],nativeLibraryDirectories=[/data/app/net.listerily.moddedbe-2/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: com.mojang.minecraftpe.AgentMainActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
It seemed that dex files weren't added to class path successfully. Though they're loaded by DexClassLoader.

**Comment by timscriptov** [comment]
You fixed it bug?
