### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by rac14** [listerily/ModdedBE#13]
I have a 64 bits Minecraft but the ModdedBE is not Working

**Comment by rac14** [comment]
Also From where can i get ModdedBE for 1.17.0.2

**Comment by rac14** [comment]
-----------------------
A fatal error occurred in ModdedBE game initializing.
Version Name: 1.0
Game Version: 1.17.0.02
EnderCore SDK: 1
OS SDK: 27
Brand: Xiaomi
Model: 
Safe Mode: 0
ABI:arm64-v8a armeabi-v7a armeabi 
-----------------------
g.a.a.b.a: Unexpected fatal error caused in game initialization.
	at g.a.a.e.b.a(Unknown Source:1185)
	at net.listerily.moddedbe.InitializingActivity$b.run(:2)
Caused by: g.a.a.b.a: Load game libraries failed.
	at g.a.a.e.b.a(Unknown Source:1056)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/net.listerily.moddedbe/code_cache/native_libs/libfmod.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1657)
	at g.a.a.e.b.a(Unknown Source:686)
	... 1 more

**Comment by timscriptov** [comment]
Your Minecraft 32 bit! Need arm64

**Comment by ProtectorYT364** [comment]
How to get 64 bits Minecraft and Give me ModdedBE for 1.17 :)

**Comment by rac14** [comment]
I guess this moddedbe is for 1.16 i need for 1.17 and also how to get Minecraft 64 bits

**Comment by timscriptov** [comment]
ModdedBE development in process...

**Comment by rac14** [comment]
Okay
