### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ghost** [listerily/ModdedBE#20]
-----------------------
A fatal error occurred in ModdedBE game initializing.
Version Name: 1.0
Game Version: 0.13.0
EnderCore SDK: 1
OS SDK: 29
Brand: realme
Model: RMX2030
Safe Mode: 0
ABI:arm64-v8a armeabi-v7a armeabi 
-----------------------
org.endercore.android.exception.LauncherException: Unexpected fatal error caused in game initialization.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:359)
	at net.listerily.moddedbe.InitializingActivity$onCreate$1.run(InitializingActivity.kt:30)
Caused by: org.endercore.android.exception.LauncherException: Load game libraries failed.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:252)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/net.listerily.moddedbe/code_cache/native_libs/libfmod.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:235)
	... 1 more

**Comment by TripleCamera** [comment]
If your device is 64-bit, you would need 64-bit Minecraft.

**Comment by TripleCamera** [comment]
@NSTAdventure I have just uploaded `ModdedBE_1.1_crack_32bit.apk` in Releases, which can launch 32-bit Minecraft on 64-bit devices. We will come up with a better solution in the future, but this issue will be closed now as a duplication of #9.

**Comment by ghost** [comment]
> @NSTAdventure I have just uploaded `ModdedBE_1.1_crack_32bit.apk` in Releases, which can launch 32-bit Minecraft on 64-bit devices. We will come up with a better solution in the future, but this issue will be closed now as a duplication of #9.

Meanwhile in the universe not even 32 bit version can run it's also crashes like before

**Comment by TripleCamera** [comment]
> Meanwhile in the universe not even 32 bit version can run it's also crashes like before

Please send the crash report here.

**Comment by ghost** [comment]
> > Meanwhile in the universe not even 32 bit version can run it's also crashes like before
> 
> Please send the crash report here.

-----------------------
A fatal error occurred in ModdedBE game initializing.
Version Name: 1.0
Game Version: 0.13.0
EnderCore SDK: 1
OS SDK: 29
Brand: realme
Model: RMX2030
Safe Mode: 0
ABI:arm64-v8a armeabi-v7a armeabi 
-----------------------
org.endercore.android.exception.LauncherException: Unexpected fatal error caused in game initialization.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:359)
	at net.listerily.moddedbe.InitializingActivity$onCreate$1.run(InitializingActivity.kt:30)
Caused by: org.endercore.android.exception.LauncherException: Load game libraries failed.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:252)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:237)
	... 1 more

**Comment by TripleCamera** [comment]
@NSTAdventure `0.13.0`? Sorry, we haven't supported that yet.

**Comment by NSTAdventure** [comment]
> @NSTAdventure `0.13.0`? Sorry, we haven't supported that yet.
Ok so what i can do for now?
Those error is really horsemen of the annoyance 🗿
Because no matter what i can't workaround it 💀

**Comment by TripleCamera** [comment]
> (Deleted comment)

@NSTAdventure I will update this project when I am free, which may be in winter vacation... If you know about Android programming, you can improve this app and submit a pull request.

For now, if you wish to launch 0.13.0, you can try (an older version of) BlockLauncher.
