### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joeyoropesa-dev** [listerily/ModdedBE#21]
-----------------------
A fatal error occurred in ModdedBE game initializing.
Version Name: 1.0
Game Version: 1.19.81.01
EnderCore SDK: 1
OS SDK: 33
Brand: Xiaomi
Model: 2109119DG
Safe Mode: 0
ABI:arm64-v8a armeabi-v7a armeabi 
-----------------------
org.endercore.android.exception.LauncherException: Unexpected fatal error caused in game initialization.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:359)
	at net.listerily.moddedbe.InitializingActivity$onCreate$1.run(InitializingActivity.kt:30)
Caused by: org.endercore.android.exception.LauncherException: Load game libraries failed.
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:252)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/user/0/net.listerily.moddedbe/code_cache/native_libs/libfmod.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at org.endercore.android.operator.Launcher.initializeGame(Launcher.java:235)
	... 1 more

**Comment by TripleCamera** [comment]
Oh my god! I don't have time for this now. Please wait until July.

**Comment by joeyoropesa-dev** [comment]
> Oh my god! I don't have time for this now. Please wait until July.

Of course, that's more better than never 🥰

**Comment by joeyoropesa-dev** [comment]
> Oh my god! I don't have time for this now. Please wait until July.

I waited even longer so is there any progress on this case?

**Comment by TripleCamera** [comment]
> I waited even longer so is there any progress on this case?

Sorry, both listerily and I are busy doing other stuff. We are not planning to work on this for now. 😞
