### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by timscriptov** [listerily/ModdedBE#8]
-----------------------
A fatal error occurred in ModdedBE game initializing.
Version Name: 1.0
Game Version: 1.16.201.01
EnderCore SDK: 1
OS SDK: 23
Brand: Xiaomi
Model: Redmi Note 4
Safe Mode: 0
ABI:arm64-v8a armeabi-v7a armeabi 
-----------------------
d.a.a.a.c.a: Unexpected fatal error caused in game initialization.
	at d.a.a.a.d.c.a(:11)
	at net.listerily.moddedbe.InitializingActivity$a.run(:6)
Caused by: d.a.a.a.c.a: Exception occurred while loading *.so file.
	... 2 more
Caused by: java.lang.ClassNotFoundException: dalvik.system.DexPathList$NativeLibraryElement
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at c.b.a.a.b.l.i.B()
	at d.a.a.a.d.c.a(:8)
	... 1 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "dalvik.system.DexPathList$NativeLibraryElement" on path: DexPathList[[dex file "/data/user/0/net.listerily.moddedbe/code_cache/endercore_launcher/dex_libs/CrackedLicense.dex", dex file "/data/user/0/net.listerily.moddedbe/code_cache/endercore_launcher/dex_libs/classes.dex", zip file "/data/app/net.listerily.moddedbe-1/base.apk"],nativeLibraryDirectories=[/data/app/net.listerily.moddedbe-1/lib/arm64, /data/app/net.listerily.moddedbe-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 6 more
	Suppressed: java.lang.ClassNotFoundException: dalvik.system.DexPathList$NativeLibraryElement
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 7 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by TimScriptov** [comment]
PS: clear in AndroidManifesr.xml isSplit="true".

**Comment by TimScriptov** [comment]
isSplit = install failed ModdedBE

**Comment by timscriptov** [comment]
Please use Signature V1+V2. V2 working for Android 7.0+

**Comment by timscriptov** [comment]
Clear in endercore/AndroidManifest.xml/application:

```
android:extractNativeLibs="false"
android:isSplitRequired="true"
```

If true = failed install ModdedBE

**Comment by timscriptov** [comment]
And delete file:
```
endercore/main/src/res/xml/splits0.xml
```

**Comment by listerily** [comment]
fixed
